// Structural checks on the static HTML pages. Without a build step the page
// shells are maintained copies (the nav and landing cards are regenerated by
// scripts/sync-pages.js), so these tests keep them from drifting apart or
// away from what the JS expects.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { PLATFORM_DEFINITIONS, formatterUrl } from '../public/js/platforms.js';
import { navPages, renderNav, syncedPage } from '../scripts/sync-pages.js';

const PUBLIC = join(import.meta.dirname, '..', 'public');
const BASE_URL = 'https://memorylimit.dev';

const read = (path) => readFileSync(join(PUBLIC, path, 'index.html'), 'utf8');
const attr = (html, pattern) => html.match(pattern)?.[1] ?? null;
const metaProperty = (html, property) => attr(html, new RegExp(`<meta property="${property}" content="([^"]*)"`));
const metaName = (html, name) => attr(html, new RegExp(`<meta name="${name}" content="([^"]*)"`));
const decode = (s) => s.replace(/&amp;/g, '&');

const CALCULATOR_PAGES = PLATFORM_DEFINITIONS.map((def) => ({ ...def, dir: def.path.slice(1, -1) }));
const CONTENT_PAGES = [
  { path: '/', dir: '' },
  { path: '/privacy/', dir: 'privacy' },
  { path: '/support/', dir: 'support' },
  ...CALCULATOR_PAGES
];
const SHAREABLE_PAGES = [{ path: '/', dir: '' }, ...CALCULATOR_PAGES];

const REQUIRED_IDS = [...readFileSync(join(PUBLIC, 'js', 'app.js'), 'utf8').matchAll(/element\('([^']+)'\)/g)].map((m) => m[1]);

test('app.js declares the element ids it needs (sanity check for the extraction below)', () => {
  assert.ok(REQUIRED_IDS.length > 20);
});

for (const page of CALCULATOR_PAGES) {
  test(`${page.path} contains every element id app.js requires`, () => {
    const html = read(page.dir);
    const missing = REQUIRED_IDS.filter((id) => !html.includes(`id="${id}"`));
    assert.deepEqual(missing, []);
  });

  test(`${page.path} declares its platform and preloads only its own formatter`, () => {
    const html = read(page.dir);
    assert.match(html, new RegExp(`<body data-platform="${page.id}">`));
    const preloads = [...html.matchAll(/<link rel="modulepreload" href="([^"]+)"/g)].map((m) => m[1]);
    assert.deepEqual(preloads, [formatterUrl(page)]);
    assert.match(html, /<script type="module" src="\/js\/calculator-page\.js"><\/script>/);
  });
}

test('no page has inline scripts or inline event handlers (the CSP forbids them)', () => {
  const offenders = [];
  for (const dir of [...CONTENT_PAGES.map((p) => p.dir), 'k8s']) {
    const html = read(dir);
    if (/<script(?![^>]*\bsrc=)[^>]*>/.test(html)) offenders.push(`${dir || '/'}: inline <script>`);
    if (/\son[a-z]+\s*=/.test(html)) offenders.push(`${dir || '/'}: inline event handler`);
    if (/href="javascript:/i.test(html)) offenders.push(`${dir || '/'}: javascript: URL`);
  }
  assert.deepEqual(offenders, []);
});

test('every page links the ICO, SVG and touch icons', () => {
  const missing = [];
  for (const dir of [...CONTENT_PAGES.map((p) => p.dir), 'k8s']) {
    const head = read(dir).split('</head>')[0];
    for (const link of [
      '<link rel="icon" href="/favicon.ico" sizes="32x32" />',
      '<link rel="icon" href="/favicon.svg" type="image/svg+xml" />',
      '<link rel="apple-touch-icon" href="/apple-touch-icon.png" />'
    ]) if (!head.includes(link)) missing.push(`${dir || '/'}: ${link}`);
  }
  assert.deepEqual(missing, []);
});

test('every page header shows the logo in both theme variants', () => {
  for (const page of CONTENT_PAGES) {
    const html = read(page.dir);
    assert.match(html, /<img class="brand__mark brand__mark--light" src="\/brand\/memorylimit-mark\.svg" alt=""/, page.path);
    assert.match(html, /<img class="brand__mark brand__mark--dark" src="\/brand\/memorylimit-mark-on-dark\.svg" alt=""/, page.path);
  }
});

test('public/ contains only the expected pages', () => {
  const expected = new Set([...CONTENT_PAGES.map((p) => p.dir), 'k8s'].map((dir) => join(dir, 'index.html')));
  const actual = readdirSync(PUBLIC, { recursive: true })
    .filter((file) => file.endsWith('.html'))
    .map((file) => join(file));
  assert.deepEqual(actual.filter((file) => !expected.has(file)), []);
});

for (const [dir, currentId] of navPages()) {
  test(`${dir ? `/${dir}/` : '/'} nav${dir ? '' : ' and platform cards'} match platforms.js`, () => {
    const html = read(dir);
    assert.equal(html, syncedPage(dir, currentId, html), 'run `npm run sync:pages`');
  });
}

test('the generated nav marks exactly one link as current on each calculator page', () => {
  for (const def of PLATFORM_DEFINITIONS) {
    const current = [...renderNav(def.id).matchAll(/href="([^"]+)"[^>]*aria-current="page"/g)].map((m) => m[1]);
    assert.deepEqual(current, [def.path]);
  }
  assert.doesNotMatch(renderNav(null), /aria-current/);
});

for (const page of CONTENT_PAGES) {

  test(`${page.path} applies the saved theme before first paint and loads the shared chrome`, () => {
    const html = read(page.dir);
    const head = html.slice(0, html.indexOf('</head>'));
    assert.match(head, /<script src="\/js\/theme-init\.js"><\/script>/);
    assert.match(html, /\/js\/(site|calculator-page)\.js/);
    assert.match(html, /id="ethical-ads-slot"/);
    assert.match(html, /id="donation-slot"/);
  });

  test(`${page.path} has a canonical URL matching its own path`, () => {
    assert.equal(attr(read(page.dir), /<link rel="canonical" href="([^"]+)"/), `${BASE_URL}${page.path}`);
  });
}

for (const page of SHAREABLE_PAGES) {
  test(`${page.path} Open Graph / Twitter tags mirror its title, description and canonical URL`, () => {
    const html = read(page.dir);
    const title = decode(attr(html, /<title>([^<]+)<\/title>/)).replace(/ \| MemoryLimit$/, '');
    const description = decode(metaName(html, 'description'));

    assert.equal(decode(metaProperty(html, 'og:title')), title);
    assert.equal(decode(metaName(html, 'twitter:title')), title);
    assert.equal(decode(metaProperty(html, 'og:description')), description);
    assert.equal(decode(metaName(html, 'twitter:description')), description);
    assert.equal(metaProperty(html, 'og:url'), `${BASE_URL}${page.path}`);
    assert.equal(metaProperty(html, 'og:image'), `${BASE_URL}/og-image.png`);
  });
}

test('every root-relative asset referenced by a page exists', () => {
  const pages = [...CONTENT_PAGES.map((p) => p.dir), 'k8s'];
  const missing = [];
  for (const dir of pages) {
    const html = read(dir);
    for (const [, ref] of html.matchAll(/(?:href|src)="(\/[^"#?]*)"/g)) {
      const target = ref.endsWith('/') ? join(PUBLIC, ref, 'index.html') : join(PUBLIC, ref);
      if (ref !== '/og-image.png' && !existsSync(target)) missing.push(`${dir || '/'} → ${ref}`);
    }
  }
  assert.deepEqual(missing, []);
});

test('every font referenced by the stylesheet exists', () => {
  const css = readFileSync(join(PUBLIC, 'css', 'styles.css'), 'utf8');
  const fonts = [...css.matchAll(/url\('(\/fonts\/[^']+)'\)/g)].map((m) => m[1]);
  assert.ok(fonts.length > 0);
  assert.deepEqual(fonts.filter((f) => !existsSync(join(PUBLIC, f))), []);
});
