// Structural checks on the static HTML pages. Without a build step the page
// shells are maintained copies (the nav and landing cards are regenerated by
// scripts/sync-pages.js), so these tests keep them from drifting apart or
// away from what the JS expects.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { PLATFORM_DEFINITIONS, formatterUrl, entryUrl, getGuidePages, SIZING_MODEL_GUIDE } from '../public/js/platforms.js';
import { navPages, renderNav, renderGuideLink, syncedPage } from '../scripts/sync-pages.js';

const PUBLIC = join(import.meta.dirname, '..', 'public');
const BASE_URL = 'https://memorylimit.dev';

const read = (path) => readFileSync(join(PUBLIC, path, 'index.html'), 'utf8');
const attr = (html, pattern) => html.match(pattern)?.[1] ?? null;
const metaProperty = (html, property) => attr(html, new RegExp(`<meta property="${property}" content="([^"]*)"`));
const metaName = (html, name) => attr(html, new RegExp(`<meta name="${name}" content="([^"]*)"`));
const decode = (s) => s.replace(/&amp;/g, '&');

const CALCULATOR_PAGES = PLATFORM_DEFINITIONS.map((def) => ({ ...def, dir: def.path.slice(1, -1) }));
const GUIDE_PAGES = [SIZING_MODEL_GUIDE, ...getGuidePages().map(({ path }) => path)].map((path) => ({ path, dir: path.slice(1, -1) }));
const CONTENT_PAGES = [
  { path: '/', dir: '' },
  { path: '/privacy/', dir: 'privacy' },
  { path: '/support/', dir: 'support' },
  ...CALCULATOR_PAGES,
  ...GUIDE_PAGES
];
const SHAREABLE_PAGES = [{ path: '/', dir: '' }, ...CALCULATOR_PAGES, ...GUIDE_PAGES];

// The ids a page script looks up with element('…'); each page must contain the ones its own entry script needs.
const requiredIds = (script) =>
  [...readFileSync(join(PUBLIC, script), 'utf8').matchAll(/element\('([^']+)'\)/g)].map((m) => m[1]);
const REQUIRED_IDS = requiredIds('js/app.js');

test('app.js declares the element ids it needs (sanity check for the extraction below)', () => {
  assert.ok(REQUIRED_IDS.length > 20);
});

for (const page of CALCULATOR_PAGES) {
  const entry = entryUrl(page);
  const ids = entry === '/js/calculator-page.js' ? REQUIRED_IDS : requiredIds(entry.slice(1));

  test(`${page.path} contains every element id its page script requires`, () => {
    const html = read(page.dir);
    const missing = ids.filter((id) => !html.includes(`id="${id}"`));
    assert.deepEqual(missing, []);
  });

  test(`${page.path} declares its platform and preloads only its own formatter`, () => {
    const html = read(page.dir);
    assert.match(html, new RegExp(`<body data-platform="${page.id}">`));
    const preloads = [...html.matchAll(/<link rel="modulepreload" href="([^"]+)"/g)].map((m) => m[1]);
    assert.deepEqual(preloads, [formatterUrl(page)]);
    assert.ok(html.includes(`<script type="module" src="${entry}"></script>`), `loads ${entry}`);
  });
}

test('no page has inline scripts or inline event handlers (the CSP forbids them)', () => {
  const offenders = [];
  for (const dir of [...CONTENT_PAGES.map((p) => p.dir), 'k8s']) {
    const html = read(dir);
    if (/<script(?![^>]*\bsrc=)[^>]*>/.test(html)) offenders.push(`${dir || '/'}: inline <script>`);
    if (/\son[a-z]+\s*=/.test(html)) offenders.push(`${dir || '/'}: inline event handler`);
    if (/href="javascript:/i.test(html)) offenders.push(`${dir || '/'}: javascript: URL`);
  }
  assert.deepEqual(offenders, []);
});

test('every page links the ICO, SVG and touch icons', () => {
  const missing = [];
  for (const dir of [...CONTENT_PAGES.map((p) => p.dir), 'k8s']) {
    const head = read(dir).split('</head>')[0];
    for (const link of [
      '<link rel="icon" href="/favicon.ico" sizes="32x32" />',
      '<link rel="icon" href="/favicon.svg" type="image/svg+xml" />',
      '<link rel="apple-touch-icon" href="/apple-touch-icon.png" />'
    ]) if (!head.includes(link)) missing.push(`${dir || '/'}: ${link}`);
  }
  assert.deepEqual(missing, []);
});

test('every page header shows the logo in both theme variants', () => {
  for (const page of CONTENT_PAGES) {
    const html = read(page.dir);
    assert.match(html, /<img class="brand__mark brand__mark--light" src="\/brand\/memorylimit-mark\.svg" alt=""/, page.path);
    assert.match(html, /<img class="brand__mark brand__mark--dark" src="\/brand\/memorylimit-mark-on-dark\.svg" alt=""/, page.path);
  }
});

test('public/ contains only the expected pages', () => {
  const expected = new Set([...CONTENT_PAGES.map((p) => p.dir), 'k8s'].map((dir) => join(dir, 'index.html')));
  const actual = readdirSync(PUBLIC, { recursive: true })
    .filter((file) => file.endsWith('.html'))
    .map((file) => join(file));
  assert.deepEqual(actual.filter((file) => !expected.has(file)), []);
});

for (const [dir, currentId] of navPages()) {
  test(`${dir ? `/${dir}/` : '/'} nav${dir ? '' : ' and platform cards'} match platforms.js`, () => {
    const html = read(dir);
    assert.equal(html, syncedPage(dir, currentId, html), 'run `npm run sync:pages`');
  });
}

test('the generated nav marks exactly one link as current on each calculator page', () => {
  for (const def of PLATFORM_DEFINITIONS) {
    const current = [...renderNav(def.id).matchAll(/href="([^"]+)"[^>]*aria-current="page"/g)].map((m) => m[1]);
    assert.deepEqual(current, [def.path]);
  }
  assert.doesNotMatch(renderNav(null), /aria-current/);
});

test('"How this was derived" links to the platform’s own guide, or the shared sizing model, in a new tab', () => {
  for (const def of PLATFORM_DEFINITIONS) {
    const link = renderGuideLink(def.id);
    assert.ok(link.includes(`href="${def.guide ?? SIZING_MODEL_GUIDE}" target="_blank" rel="noopener"`), def.id);
    assert.ok(link.includes('<span class="visually-hidden"> (opens in a new tab)</span>'), def.id);
  }
});

test('the explanation is a <div>, so a formatter’s steps can render as a list inside it', () => {
  for (const page of CALCULATOR_PAGES) assert.match(read(page.dir), /<div class="explanation" id="explanation">/, page.path);
});

for (const page of CONTENT_PAGES) {

  test(`${page.path} applies the saved theme before first paint and loads the shared chrome`, () => {
    const html = read(page.dir);
    const head = html.slice(0, html.indexOf('</head>'));
    assert.match(head, /<script src="\/js\/theme-init\.js"><\/script>/);
    assert.match(html, /\/js\/(site|calculator-page|couchbase-page)\.js/);
    assert.match(html, /id="ethical-ads-slot"/);
    assert.match(html, /id="donation-slot"/);
  });

  test(`${page.path} has a canonical URL matching its own path`, () => {
    assert.equal(attr(read(page.dir), /<link rel="canonical" href="([^"]+)"/), `${BASE_URL}${page.path}`);
  });
}

for (const page of SHAREABLE_PAGES) {
  test(`${page.path} Open Graph / Twitter tags mirror its title, description and canonical URL`, () => {
    const html = read(page.dir);
    const title = decode(attr(html, /<title>([^<]+)<\/title>/)).replace(/ \| MemoryLimit$/, '');
    const description = decode(metaName(html, 'description'));

    assert.equal(decode(metaProperty(html, 'og:title')), title);
    assert.equal(decode(metaName(html, 'twitter:title')), title);
    assert.equal(decode(metaProperty(html, 'og:description')), description);
    assert.equal(decode(metaName(html, 'twitter:description')), description);
    assert.equal(metaProperty(html, 'og:url'), `${BASE_URL}${page.path}`);
    assert.equal(metaProperty(html, 'og:image'), `${BASE_URL}/og-image.png`);
  });
}

test('every root-relative asset referenced by a page exists', () => {
  const pages = [...CONTENT_PAGES.map((p) => p.dir), 'k8s'];
  const missing = [];
  for (const dir of pages) {
    const html = read(dir);
    for (const [, ref] of html.matchAll(/(?:href|src)="(\/[^"#?]*)"/g)) {
      const target = ref.endsWith('/') ? join(PUBLIC, ref, 'index.html') : join(PUBLIC, ref);
      if (ref !== '/og-image.png' && !existsSync(target)) missing.push(`${dir || '/'} → ${ref}`);
    }
  }
  assert.deepEqual(missing, []);
});

test('every font referenced by the stylesheet exists', () => {
  const css = readFileSync(join(PUBLIC, 'css', 'styles.css'), 'utf8');
  const fonts = [...css.matchAll(/url\('(\/fonts\/[^']+)'\)/g)].map((m) => m[1]);
  assert.ok(fonts.length > 0);
  assert.deepEqual(fonts.filter((f) => !existsSync(join(PUBLIC, f))), []);
});

for (const page of GUIDE_PAGES) {
  test(`${page.path} marks sources with links: docs to the document, assumptions to their row and back`, () => {
    const html = read(page.dir);
    const body = html.slice(html.indexOf('<div class="wrap guide">'));
    const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
    // Only the intro's legend may show a tag that isn't a link.
    assert.doesNotMatch(body, /<span class="guide-tag/);
    const docs = [...body.matchAll(/<a class="guide-tag guide-tag--doc" href="([^"]+)"/g)].map((m) => m[1]);
    assert.ok(docs.length > 0);
    for (const href of docs) assert.match(href, /^https:\/\//);
    assert.match(body, /id="assumptions"/);

    // Each "Assumption" label links to its own row of the table…
    const labels = [...body.matchAll(/<a class="guide-tag guide-tag--assumption"(?: id="[^"]+")? href="#([^"]+)"/g)].map((m) => m[1]);
    assert.ok(labels.length > 0);
    for (const target of labels) {
      assert.match(target, /^assumption-\d+$/);
      assert.ok(ids.has(target), `#${target} is missing`);
    }
    // …and every row links back to a label in the text.
    const table = body.slice(body.indexOf('id="assumptions"'));
    const rows = [...table.slice(0, table.indexOf('</table>')).matchAll(/<tr id="(assumption-\d+)"><td>([\s\S]*?)<\/td>/g)];
    assert.equal(rows.length, [...table.slice(0, table.indexOf('</table>')).matchAll(/<tr[ >]/g)].length - 1, 'every row has an id');
    for (const [, rowId, cell] of rows) {
      assert.ok(labels.includes(rowId) || /href="#assumption-\d+-ref"/.test(cell), rowId);
      const back = cell.match(/<a class="guide-backref" href="#([^"]+)"/)?.[1];
      assert.ok(back && ids.has(back), `${rowId} links back to a missing #${back}`);
    }
  });
}

const ASSUMPTION_KINDS = ['Our default', 'Our reading', 'About your setup'];

for (const page of GUIDE_PAGES) {
  test(`${page.path} gives every assumption a kind`, () => {
    const html = read(page.dir);
    const section = html.slice(html.indexOf('id="assumptions"'));
    const table = section.slice(0, section.indexOf('</table>'));
    assert.match(table, /<th scope="col">Assumption<\/th><th scope="col">Kind<\/th>/);
    const rows = [...table.matchAll(/<tr(?: id="[^"]+")?><td>/g)].length;
    const kinds = [...table.matchAll(/<td class="guide-kind">([^<]+)<\/td>/g)].map((m) => m[1]);
    assert.ok(rows > 0);
    assert.equal(kinds.length, rows);
    for (const kind of kinds) assert.ok(ASSUMPTION_KINDS.includes(kind), kind);
  });
}

test('every calculator has its advanced section, closed by default, with a reset button', () => {
  for (const page of CALCULATOR_PAGES) {
    const html = read(page.dir);
    const section = html.match(/<details class="advanced" id="advanced-settings"[^>]*>([\s\S]*?)<\/details>/);
    assert.ok(section, page.path);
    assert.doesNotMatch(section[0].split('>')[0], /\sopen\b/, `${page.path}: closed by default`);
    assert.match(section[1], /data-advanced-count/, page.path);
    assert.match(section[1], /<button[^>]*data-advanced-reset[^>]*>Reset to defaults<\/button>/, page.path);
  }
});
